.\" Copyright © 2008 Per Andersson <avtobiff@gmail.com>
.\" This man page is covered by the GNU General Public License (GPLv2 or higher).
.TH micro_evtd.event 8 "July 2008" "Debian Project" ""

.SH NAME

micro_evtd.event - Event script for micro_evtd

.SH SYNOPSIS

micro_evtd.event [
.B OPTION
]

.SH DESCRIPTION

The event script works as a front end for micro_evtd.

.SH MESSAGE EVENTS

The event system has been modified such that 99% of the daemon event system is pushed through the event script.
A third parameter is supplied by the daemon out to the script detailing information relevant to the generated
message.

.TP 5

.IR 4

Fan failure

.TP 5

.IR C

Copy to RAMDISK.

.TP 5

.IR O

Overheat

.TP 5

.IR I

Updates
.B my_status
with temperature and fan speed information.

.TP 5

.IR B

Button press information.

.TP 5

.IR W

Message event.

.TP 5

.IR S

Standby event.

.IR T

If enabled, display time remaining before entering low power mode.

.SH SEE ALSO

microapl(8), micro_evtd(8), micro_evtd.conf(5)

.SH AUTHOR

Bob Perry <lb-source@users.sourceforge.net>
