.\" Copyright © 2008 Per Andersson <avtobiff@gmail.com>
.\" This man page is covered by the GNU General Public License (GPLv2 or higher).
.TH micro_evtd.conf 5 "July 2008" "Debian Project" ""

.SH NAME

micro_evtd.conf - Configuration file for micro_evtd

.SH THE CONFIGURATION FILE

The
.IR micro_evtd
configuration file is at initial start-up. The file format is similar
to other Unix configuration files -  comments begin with a # character and extend to
the end of the line; blank lines are ignored.  Configuration commands consist of an initial
keyword followed by an argument.  Arguments may be strings or integer values.  Optional
arguments are delimited by [ ] in the following descriptions, while alternatives are
separated by |.

.TP 5

.IR TMP
[path]

Specifies the location of where the temporary files will be stored.  This
should normally be set the location of the RAMDISK volume and only changed
for debugging.

.TP 5

.IR LOG
[path]

Specifies the location of the debugging log file.

.TP 5

.IR DEBUG
[0..9]

Debug enable.  For advanced use only.

.TP 5

.IR MONITOR
[ON|OFF]

Defaults to ON and allows the user to override the daemon's fan control.  Set
to OFF to disable this feature.

.TP 5

.IR REFRESH
[3..100|OFF]

Specifies the refresh cycle time in seconds.  Adjust this if you want to
reduce the sample frequency of the temperature control.

When set to OFF, the micro's watchdog is disabled and the daemon refresh
rate is controlled by the fan stop time.

.TP 5

.IR FANSTOP
[0..30]

Specifies the amount of time elapsed for a stalled/stationary fan.  If the
fan is deemed to have not restarted after this amount of time then the
box will be powered down by an event.

.TP 5

.IR TEMP-RANGE
[t1 t2 t3 t4]

Specifies the temperature break points for slow, fast, full and overheat.  As
the current temperature rises above t1 then the fan is switched from off
to slow speed.  As the temperature moves through t2 then the fan is switched
to fast speed and so on.  If the temperature rises above t4 then the box is
powered down due to overheat by an event.

.TP 5

.IR TREND
[YES|NO]

Defaults to YES.  This changes the temperature monitoring to an averaging
sample switching of the fan rather than instant temperature reading.  This
is useful to prevent premature switching and to maintain a steady box
temperature and fan speed.

.TP 5

.IR HYSTERESIS
[0..5]

Default to two degree.  This defines the amount of temperature swing between
the fan control temperatures.

.TP 5

.IR [<day> | <day>-<day>]
[ON=HH:MM | OFF=HH:MM | OFF>HH:MM]

This defines events for either a single day or group of days, '-' seperator.
Any number of
.B ON
and
.B OFF
events can be specified and can be extended over additional lines. <day> can
be any number of days of the week specified as either SUN, MON, TUE, WED, THR,
FRI, and SAT.  For example:

.RS 15
.B MON-WED=ON=09:00,OFF=23:00
.RE
.RS 15
.B THR=ON=09:00
.RE
.RS 15
.B FRI=OFF>01:00
.RE

.RS 5

In this example, the first standby event is monday at 09:00.  At 23:00 the
Linkstation will enter standby.  This is repeated for tuesday and wednesday.  On
thursday, the Linkstation will resume at 09:00 and will enter standby on friday
after 1 hour following a wake-up event; this event can either be a button event
or an outside event such as Wake-On-Lan.  The unit will then remain in standby for
saturaday and sunday and not resume again till 09:00 on monday.  This time
MUST be specified in UTC format and follow HH:MM.
.LP
Five minutes before power off is required, a message is broadcast to all console
users.  At shutdown, an event message is sent to the event script.
.B See micro_evtd.event(8) for more details.

.SH SEE ALSO

microapl(8), micro_evtd(5), micro_evtd.event(8)

.SH AUTHOR

Bob Perry <lb-source@users.sourceforge.net>
