#!/bin/sh

# Usage: debian/urepack [--upstream-version version] filename [version]

unset filename version temp

# parse arguments
if [ "$1" = "--upstream-version" ]
then
	version="$2"
	shift 2
fi
filename="$1"
[ -n "$2" ] && version="$2"

# check required arguments
if [ -z "$version" -o -z "$filename" ]
then
	echo "Usage: $0 [--upstream-version version] filename [version]" >&2
	exit 1
fi

# prepare temporary directory
temp="$(mktemp -d /tmp/urepack.XXXXXXXX)"

# repack archive: rename tag directory <version> to micro-evtd-<version>
tar -xzf "$filename" -C "$temp" && \
	mv "$temp/$version" "$temp/micro-evtd-$version" && \
	tar -czf "$filename" -C "$temp" "micro-evtd-$version" ; \
	ret=$?

# clean up and exit
rm -rf "$temp"
exit $ret
