.\" Title: microapl
.\"Author: Bob Perry
.TH MICROAPL 8 "November 2008" "3.3" "User Commands"
.SH NAME
microapl \- wrapper script for micro_evtd
.SH SYNOPSIS
microapl
.RB [ \-v ]
.RB [ \-a\ \fIoption\fR ]
.SH DESCRIPTION
Wrapper script for micro_evtd.
.SH OPTIONS
.TP 5
.B boot_end
.TP 5
.B power_off
.TP 5
.B shutdown_wait
.TP 5
.B shutdown_cancel
.TP 5
.B skip_standby
.TP 5
.B delay_standby [arg]
.TP 5
.B standby
.TP 5
.B standby_remaining
.TP 5
.B reboot
.TP 5
.B temp_get
.TP 5
.B fan_set_speed [arg]
.TP 5
.B fan_get_speed
.TP 5
.B bz_on [arg]
.TP 5
.B bz_set_freq [arg]
.TP 5
.B bz_melody tempo note ...
.TP 5
.B bz_imhere tempo note ...
.TP 5
.B int_get_switch_status [arg]
.TP 5
.B led_set_bright [arg]
.TP 5
.B led_set_cpu_mcon [arg]
.TP 5
.B led_set_on_off [arg]
.TP 5
.B led_set_blink [arg]
.TP 5
.B led_set_code_error [arg]
.TP 5
.B led_set_code_information [arg]
.TP 5
.B led_set_cpu_mcon [arg]
.TP 5
.B mcon_get_status
.TP 5
.B hdd_set_power [arg]
.TP 5
.B mcon_get_version
.SH SEE ALSO
.TP 5
\fBmicro_evtd\fR(8), \fBmicro_evtd.conf\fR(5), \fBmicro_evtd.event\fR(8).
.SH AUTHOR
Bob Perry <lb-source@users.sourceforge.net>
.LP
This manual page was written by Per Andersson <avtobiff@gmail.com>, for the
Debian project (but may be used by others).