.\" Title: micro_evtd.event
.\"Author: Bob Perry
.TH MICRO_EVTD.EVENT 8 "February 2009" "3.3" "Event Usage"
.nh
.ad l
.SH NAME
micro_evtd.event \- Event script for micro_evtd
.SH SYNOPSIS
micro_evtd.event
.RB [ \-s\ \fIoption1,option2,...\fR ]
.SH DESCRIPTION
The event script works as a front end for micro_evtd.
.SH MESSAGE EVENTS
The event system has been modified such that 99% of the daemon event system is
pushed through the event script. A third parameter is supplied by the daemon
out to the script detailing information relevant to the generated
message.
.TP 5
.IR 4
Fan failure.
.TP 5
.IR C
Copy image to RAMDISK.
.TP 5
.IR O
Overheat detection.
.TP 5
.IR I
Updates
.B my_status
with temperature,fan speed and fan failure information.
.TP 5
.IR B
Button press information.
.TP 5
.IR W
Message event.
.TP 5
.IR S
Standby event.
.TP 5
.IR T
If enabled, display time remaining before entering low power mode.
.TP 5
.IR P
Create daemon PID file.
.TP 5
.IR L
Locate present process.
.SH SEE ALSO
.TP 5
\fBmicroapl\fR(8), \fBmicro_evtd.conf\fR(5), \fBmicro_evtd\fR(8).
.SH AUTHOR
Bob Perry <lb-source@users.sourceforge.net>