.\" Title: micro-evtd.conf
.\"Author: Bob Perry
.TH MICRO-EVTD.CONF 5 "February 2009" "3.3" "Configuration"
.nh
.ad l
.SH NAME
micro-evtd.conf \- Configuration file for micro-evtd
.SH THE CONFIGURATION FILE
The
.IR micro-evtd
configuration file is at initial start\-up.  The file should be always located
within the /etc/ directory and a sample file is provided.  The file
format is similar to other Unix configuration files \-  comments begin with a #
character and extend to the end of the line; blank lines are ignored.
Configuration commands consist of an initial keyword followed by an argument.
Arguments may be strings or integer values.  Optional arguments are delimited
by [ ] in the following descriptions, while alternatives are separated by |.
.TP 5
.IR TMP\ [path]
Specifies the location of where the temporary files will be stored.  This
should normally be set the location of the RAMDISK volume and only changed
for debugging.
.TP 5
.IR LOG\ [path]
Specifies the location of the debugging log file.
.TP 5
.IR DEBUG\ [0..9]
Debug enable.  For advanced use only.
.TP 5
.IR MONITOR\ [1..4|ON|OFF]
Defaults to ON and allows the user to override the daemon's fan control.  Set
to OFF to disable this feature.

The values 1 through 4 correspond to fan speeds.  This allows the user to set
a minimum fan speed for the unit:

.RS 15
.B 1\ - STOP
.RE
.RS 15
.B 2\ - SLOW
.RE
.RS 15
.B 3\ - FAST
.RE
.RS 15
.B 4\ - FULL
.RE
.RS 5

Full temperature control and overheat warning still applies when operating in
this state.
.RE
.TP 5
.IR REFRESH\ [3..100|OFF] [ON|OFF]
Specifies the refresh cycle time in seconds.  Adjust this if you want to
reduce the sample frequency of the temperature control.

When set to OFF, the micro's watchdog is disabled and the daemon refresh
rate is controlled by the fan stop time.

The second parameter, default is ON, allows the user to enable or disable
the output status \fBmicro-evtd.status\fR.
.TP 5
.IR FANSTOP\ [0..30]
Specifies the amount of time elapsed for a stalled/stationary fan.  If the
fan is deemed to have not restarted after this amount of time then the
box will be powered down by an event.
.TP 5
.IR TEMP-RANGE\ [t1\ t2\ t3\ t4]
Specifies the temperature break points for slow, fast, full and overheat.  As
the current temperature rises above t1 then the fan is switched from off
to slow speed.  As the temperature moves through t2 then the fan is switched
to fast speed and so on.  If the temperature rises above t4 then the box is
powered down due to overheat by an event.
.TP 5
.IR TREND\ [YES|NO]
Defaults to YES.  This changes the temperature monitoring to an averaging
sample switching of the fan rather than instant temperature reading.  This
is useful to prevent premature switching and to maintain a steady box
temperature and fan speed.
.TP 5
.IR HYSTERESIS\ [0..5]
Default to two degree.  This defines the amount of temperature swing between
the fan control temperatures.
.TP 5
.IR BUTTON\ [STANDBY|SHUTDOWN]
Default is shutdown.  This defines the action taken when the power button is
pressed.  If standby, then when the power button is hit and standby is enabled
the box will enter standby.  Otherwise, it will simply shutdown.
.TP 5
.IR [<day> | <day>-<day>]\ [ON=HH:MM | OFF=HH:MM | OFF>HH:MM]
This defines events for either a single day or group of days, '-' seperator.
Any number of
.B ON
and
.B OFF
events can be specified and can be extended over additional lines. <day> can
be any number of days of the week specified as either SUN, MON, TUE, WED, THR,
FRI, and SAT.  For example:

.RS 15
.B MON-WED=ON=09:00,OFF=23:00
.RE
.RS 15
.B THR=ON=09:00
.RE
.RS 15
.B FRI=OFF>01:00
.RE
.RS 5

In this example, the first standby event is Monday at 09:00.  At 23:00 the
Linkstation will enter standby.  This is repeated for Tuesday and Wednesday.
On Thursday, the Linkstation will resume at 09:00 and will enter standby on
Friday after 1 hour following a wake\-up event; this event can either be a
button event or an outside event such as Wake\-On\-Lan.  The unit will then
remain in standby for saturaday and sunday and not resume again till 09:00 on
monday.  This time MUST be specified in UTC format and follow HH:MM.

Five minutes before power off is required, a message is broadcast to all
console users.  At shutdown, an event message is sent to the event script.
.B See micro-evtd.event(8) for more details.
.RE
.TP 5
.IR DELAY_STANDBY\ [<name>][,<name>][.....]
This is a comma seperated list of process names that if present at standby
will prevent the box from entering the standby state.  The list will be
polled every five minutes from the off event time.  If all the processes
are removed before the next event off time then the box will enter standby
immediately.  If the box is kept up beyond the next power on event then
this process stops.
.SH SEE ALSO
.TP 5
\fBmicroapl\fR(8), \fBmicro-evtd\fR(8), \fBmicro-evtd.event\fR(8).
.SH AUTHOR
Bob Perry <lb-source@users.sourceforge.net>
